name: TororoPluginAPI
version: "1.0"
main: tororo1066.tororoplugin.TororoPlugin
api-version: "1.19"
loader: tororo1066.tororoplugin.DependencyLoader

dependencies:
  server:
    NMSUtils:
      load: BEFORE