name: TororoPluginAPI
version: 1.0
main: tororo1066.tororoplugin.TororoPlugin
api-version: 1.17
softdepend:
  - Essentials
  - NMSUtils
permissions:
  tororo.op:
    default: op

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.20
  - com.ezylang:EvalEx:3.1.2
  - org.mongodb:mongodb-driver-sync:4.11.1