# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0

    - name: Give Permission
      run: chmod +x ./gradlew
    - name: Build CommandAPI
      run: ./gradlew CommandAPI:build
    - name: Build NMSUtils
      run: ./gradlew NMSUtils:base:build
    - name: Build TororoPluginAPI
      run: ./gradlew TororoPluginAPI:build

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: TororoPluginAPI Publish to GitHub Packages
      run: ./gradlew TororoPluginAPI:publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.TOKEN }}
        VERSION: ${{ env.SHORT_SHA }}
    - name: NMSUtils Publish to GitHub Packages
      run: ./gradlew NMSUtils:base:publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.TOKEN }}
        VERSION: ${{ env.SHORT_SHA }}
    - name: CommandAPI Publish to GitHub Packages
      run: ./gradlew CommandAPI:publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.TOKEN }}
        VERSION: ${{ env.SHORT_SHA }}
